- secret:
    name: neutron-policy-server-pypi
    data:
      api_token: !encrypted/pkcs1-oaep
        - PZ8K6Lgne8TPgUCEv/CLKALS6h2yODmFEuF8Kr+6E19epIcw2Q6fRj3s6f0CNCJTYXBJl
          UuPbW0c+ZR85mOL5nehStFYm56GmDzBtJ/aIGfquLKVmEhM4FRpFdmvfHc1olae9XTTgy
          rzqIQRKY3gdoiQJuSIBqu3k4WMkwifxrfX3BTd9uu0e0LLcOxbb6G4Ap4HUOStuASTwdZ
          fqAuN7g8z9ZiKw3HQb+QClVynsvn2DQXhZe8Ke+MnUlme5Ho6IyOJkly2R1sMjhXGvR9T
          YgqMcoGIqcOu9Pgz06LEbxEzdXRGh57A84jG0zzYGO7cXzo+WP4EiXgT6foMnKvdC9Nfx
          cWrpnwqfmNswBUGtp2FBwZdczSaR0Ri8GCmZihKU7pvxv5H4GtZ6hPeiKzdrtBUuWu7bG
          xszop5GxkKiEHbwb3yyB+8raCtmJ6+/IhPSNffVJhk3N6exLLKO5SR6vt7aUhi7vlRYTg
          4ylXSy/BSUukf9udUhE/QNmCKB90tZvBn/dRdyB7wZfgdNVhSys3B1YdF4pTgiZJWZGXY
          wyGQTKyqOVu25SQuuexJB9rmddmViMPd6a7DakW2YsoiOQ4iApX9Y7gvzmrEuwGniL/Dw
          9eg4n8rOOfd3VUNAUrxVBrGpI4ZbSXSU215nyhdqu81JsU7zfjG5s+nEOAVtXE=

- job:
    name: neutron-policy-server-build
    parent: build-python-release
    vars:
      release_python: python3

- job:
    name: neutron-policy-server-release
    parent: neutron-policy-server-build
    post-run: playbooks/release/post.yaml
    secrets:
      - secret: neutron-policy-server-pypi
        name: pypi_info

- project:
    check:
      jobs:
        - neutron-policy-server-build
        - tox-linters
        - tox-py310
        - tox-py311
    gate:
      jobs:
        - neutron-policy-server-build
        - tox-linters
        - tox-py310
        - tox-py311
    release:
      jobs:
        - neutron-policy-server-release
