- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - tox-py310
          tox-py311
    gate:
      jobs:
        - tox-linters
        - tox-py310
          tox-py311
